# Generated by Django 4.0.3 on 2022-03-31 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPredictionDataSet',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Customer.customer')),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('SeniorCitizen', models.IntegerField(blank=True, null=True)),
                ('Partner', models.CharField(blank=True, max_length=50, null=True)),
                ('Dependents', models.CharField(blank=True, max_length=50, null=True)),
                ('tenure', models.IntegerField(blank=True, null=True)),
                ('PhoneService', models.CharField(blank=True, max_length=50, null=True)),
                ('MultipleLines', models.CharField(blank=True, max_length=50, null=True)),
                ('InternetService', models.CharField(blank=True, max_length=50, null=True)),
                ('OnlineSecurity', models.CharField(blank=True, max_length=50, null=True)),
                ('OnlineBackup', models.CharField(blank=True, max_length=50, null=True)),
                ('DeviceProtection', models.CharField(blank=True, max_length=50, null=True)),
                ('TechSupport', models.CharField(blank=True, max_length=50, null=True)),
                ('StreamingTV', models.CharField(blank=True, max_length=50, null=True)),
                ('StreamingMovies', models.CharField(blank=True, max_length=50, null=True)),
                ('Contract', models.CharField(blank=True, max_length=50, null=True)),
                ('PaperlessBilling', models.CharField(blank=True, max_length=50, null=True)),
                ('PaymentMethod', models.CharField(blank=True, max_length=50, null=True)),
                ('MonthlyCharges', models.FloatField(blank=True, null=True)),
                ('TotalCharges', models.FloatField(blank=True, null=True)),
                ('Churn', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
