# Generated by Django 3.2.6 on 2021-12-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=50, null=True)),
                ('eemail', models.EmailField(max_length=50, null=True)),
                ('econtact', models.IntegerField(null=True)),
                ('eaddress', models.CharField(max_length=100, null=True)),
                ('eimage', models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/')),
                ('esal', models.FloatField(null=True)),
                ('eaddr', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
