# Generated by Django 3.2.6 on 2022-01-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_auto_20211222_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='eaddress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='econtact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='eemail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='eid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='eimage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='ename',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='esal',
            new_name='salary',
        ),
    ]
